config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  patch 'spots/:id', to: "spots#update"

  resources :spots, only: %i[index show] do
    member do
      post 'toggle_favorite', to: "spots#toggle_favorite"
      post 'dislike', to: "spots#dislike"
      post 'update_state'
      resources :favorite_folders, only: :create
    end

    resources :favorites, only: :index
  end

  resources :folders
  resources :users, only: :update

  get '/cats', to: "pages#cats"
  get '/profile', to: 'pages#profile'
  get '/favorites', to: 'spots#favorites'

  resources :favorites, only: :update
  # get '/bookmarksfolders', to: 'folders#index', as: :folders
  # get '/bookmarks/folders/:id', to: 'folders#show', as: :folder
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :favorites
  has_many :bookmarks
  acts_as_favoritable
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!

  def index
    @spots = Spot.all
    # @client = GooglePlaces::Client.new(ENV.fetch('API_KEY'))
    # @places = @client.spots_by_query(current_user.location, radius: 500)
    # @places.each do |place|
    #   next if place.photos.empty?

    #   Spot.create(
    #     name: place.name,
    #     spot_location: place.vicinity,
    #     latitude: place.lat,
    #     longitude: place.lng,
    #     description: "https://maps.googleapis.com/maps/api/place/details/",
    #     photo: "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&maxheight=400&photo_reference=#{place.photos[0].photo_reference}&key=#{ENV.fetch('API_KEY')}",
    #     rating: place.rating
    #   )
    # end
  end

  def show
    @spot = Spot.find(params[:id])
    @favorite = current_user.all_favorites.find_by(favoritable: @spot)
    @favorite_folder = FavoriteFolder.new(favorite: @favorite)
  end

  def favorites
    @favorites = current_user.all_favorites
  end

  def toggle_favorite
    @spot = Spot.find(params[:id])
    if current_user.favorited?(@spot)
      current_user.unfavorite(@spot)
      redirect_to favorites_path
    else
      current_user.favorite(@spot)
      redirect_to spots_path
    end
  end

  def dislike
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to spots_path
  end

  def bookmarks
    @favorites = current_user.all_favorites
  end

  def update
    @spot = Spot.find(params[:id])
    @favorite = current_user.favorites.find_by(favoritable_id: @spot.id)
    @favorite.update(favorite_params)
    @favorite.save
  end

  private

  def spot_params
    params.require(:spot).permit(:id, :name, :description, :price, :category, :tag, photos: [])
  end

end

app/views/spots/bookmarks.html.erb
<div style="margin-bottom:30px">
  <h2>Your Bookmarked Spots</h2>
  <% @favorites.each do |favorite| %>
    <% next unless favorite.bookmarked %>
    <div class="fav-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= asset_path(favorite.favoritable.photo) %>)">
      <%= link_to spot_path(favorite.favoritable_id), style:"text-decoration:none; color:white;" do %>
        <p><%= favorite.favoritable.name %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/spots/favorites.html.erb
<div style="padding-bottom: 98px; padding-top: 16px;">
  <% @favorites.each do |favorite| %>
    <div class="fav-card" style="position:relative; background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= asset_path(favorite.favoritable.photo) %>)">
      <%= link_to spot_path(favorite.favoritable_id), style:"text-decoration:none; color:white;" do %>
        <p><%= favorite.favoritable.name %></p>
      <% end %>
      <%= link_to toggle_favorite_spot_path(favorite.favoritable), data:{turbo_method: :post}, style:"position:absolute; top: 0px; right: 8px;" do %>
        <i class="fa-solid fa-xmark" style="color: #ffffff; font-size: 22px;"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/spots/index.html.erb
<div style="position:relative; height: 100%">
  <% @spots.each do |spot| %>
    <% next if current_user.favorites.map { |favorite| favorite.favoritable.name }.include?(spot.name) %>
    <%= link_to spot_path(spot.id), style:"text-decoration:none" do %>
      <div class="card-index" style="position:absolute; background-image: url('<%= spot.photo %>'); background-size: cover;">
        <div class="card-info">
          <span class="badge rounded-pill pink ms-2"><%= spot.category %></span>
          <h1><%= spot.name %></h1>
          <p style="padding-bottom: 4px; padding-top: 0px;">📍<%= spot.spot_location %></p>
        </div>
      </div>
    <% end %>
    <div class="position-absolute w-100" style="bottom: 10px">
      <%= link_to toggle_favorite_spot_path(spot), data: { turbo_method: :post }, class: "choice-button like-button", style: "right: 30px;" do %>
        <i class="fa-solid fa-heart"></i>
      <% end %>
      <%= link_to dislike_spot_path(spot), data: { turbo_method: :post }, class: "choice-button no-button", style: "left: 30px;" do %>
        <i class="fa-solid fa-xmark"></i>
      <% end %>
    </div>
  <% end %>
</div>



<br>
<h3 class="position-absolute" style="top: 0px; z-index: -10">No more results in your area...</h3>

<script src="path/to/hammer.js"></script>

app/views/spots/show.html.erb
<div style="padding-bottom: 100px">
  <div class="card-trip" style="position: relative;">
    <%= image_tag  @spot.photo %>
    <%= link_to :back do %>
      <i class="fa-solid fa-chevron-left" style="position: absolute; top: 15px; left: 15px; color: white; font-size: 35px;"></i>
      <% end %>
    <h2 class="card-trip-pricing" style="position: absolute; top: 438px; right: 10px; color: white; font-size: 22px;"><%= @spot.rating %>⭐️</h2>
    <div class="card-trip-infos">

      <h3><%= @spot.name %></h3>
      <h6 class='cat-tag-show'> <%= @spot.category %><h6>
      <p><i class="fa-sharp fa-solid fa-info" style="color:#0074b7">&nbsp;&nbsp;</i><%= @spot.description %></p>
      <br>
      <p><i class="fa-solid fa-location-dot" style="color:#0074b7">&nbsp;</i><%= @spot.spot_location %></p>
      <br>
      <h5>Bookmark this Spot: </h5>
      <%# the form to bookmark %>
      <% if @favorite.present? %>
        <%= simple_form_for @favorite_folder do |f| %>
          <%= f.association :folder %>
          <%= f.submit 'Add to Folder', class: "btn-blue" %>
        <% end %>
      <% end %>
      <%# the buttons  %>
      <% if current_user.favorites.find_by(favoritable_id: @spot.id) %>
        <%= link_to 'Remove from Liked', toggle_favorite_spot_path(@spot), data:{turbo_method: :post}, class:"btn-black text-decoration-none" %>
      <% else %>
        <%= link_to 'Add to Liked', toggle_favorite_spot_path(@spot), data:{turbo_method: :post}, class:"btn-blue text-decoration-none" %>
      <% end %>



    </div>
  </div>
</div>


<script>
  function reloadPage() {
    location.reload();
  }
</script>

app/views/spots/test.html.erb
<div style="position:relative, height: 100%" id="swipe-container" class="motion-swipe">
  <div data-controller="swiper" id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @spots.each do |spot| %>
        <% next if current_user.favorites.map { |favorite| favorite.favoritable.name }.include?(spot.name) %>
        <div class="carousel-item <%= "active" if @spots.first == spot %>">
          <% " data-spotId="<%= spot.id %>
          <%= image_tag spot.photo, class: "d-block w-100 card-index", style: "object-fit: cover" %>
          <h1><%= spot.name %></h1>

          <%= link_to toggle_favorite_spot_path(spot), id: "like-spot-#{spot.id}", data: { turbo_method: :post }, style: "position: absolute; bottom: 138px; right: 86px;" do %>
            <i class="fa-brands fa-gratipay" style="color: #38b4ff; font-size: 62px;"></i>
          <% end %>
          <%= link_to dislike_spot_path(spot), id: "dislike-spot-#{spot.id}", data: { turbo_method: :post }, style: "position: absolute; bottom: 138px; left: 86px;" do %>
            <i class="fa-solid fa-circle-xmark" style="color: #e61e1e; font-size: 62px;"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%# <%= "active" if @spots.first == spot %>

    <div class="position-absolute w-100" style="bottom: 10px">
      <%= link_to "#" , data: { url: toggle_favorite_spot_path(spot), turbo_method: :post, action: "click->swiper#swipeRight" },
        class: "choice-button like-button js-right-trigger", style: "right: 30px;" do %>
        <i class="fa-solid fa-heart"></i>
      <% end %>
      <%= link_to "#", data: { url: dislike_spot_path(spot), turbo_method: :post, action: "click->swiper#swipeLeft" },
        class: "choice-button no-button js-left-trigger", style: "left: 30px;" do %>
        <i class="fa-solid fa-xmark"></i>
      <% end %>
    </div>