config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  patch 'spots/:id', to: "spots#update"

  resources :spots, only: %i[index show] do
    member do
      post 'toggle_favorite', to: "spots#toggle_favorite"
      post 'dislike', to: "spots#dislike"
      post 'update_state'
      resources :favorite_folders, only: :create
    end

    resources :favorites, only: :index
  end

  resources :folders
  resources :users, only: :update

  get '/cats', to: "pages#cats"
  get '/profile', to: 'pages#profile'
  get '/favorites', to: 'spots#favorites'

  resources :favorites, only: :update
  # get '/bookmarksfolders', to: 'folders#index', as: :folders
  # get '/bookmarks/folders/:id', to: 'folders#show', as: :folder
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :favorite_folders
  has_many :favorites, through: :favorite_folders
  belongs_to :user

  def spots
    favorites.map(&:favoritable).uniq
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: %i[show edit update destroy]

  def index
    @folders = Folder.all.where(user_id: current_user)
  end

  def show
    @spots = @folder.spots
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(folder_params)
    @folder.user = current_user

    if @folder.save
      redirect_to folders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @folder.update(folder_params)
    redirect_to folders_path
  end

  def destroy
    @folder.destroy
    redirect_to folders_path
  end

  private

  def set_folder
    @folder = Folder.find(params[:id])
  end

  def folder_params
    params.require(:folder).permit(:name, :user_id)
  end
end

app/views/folders/edit.html.erb
<%= simple_form_for @folder do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/folders/index.html.erb
<div style="padding:30px 0px">
  <h2>Your Collections</h2>
  <% @folders.each do |folder| %>
    <div class="folder-card" style="position:relative;">
      <%= link_to folder_path(folder), style:"text-decoration:none; color:white;" do %>
        <h1><%= folder.name %></h1>
      <% end %>
      <%= link_to folder_path(folder), data: { turbo_method: :delete }, style: "position:absolute; top: 0px; right: 8px;" do %>
        <i class="fa-solid fa-xmark" style="color: #00b8ff; font-size: 22px;"></i>
      <% end %>
      <%= link_to edit_folder_path(folder), style: "position:absolute; bottom: 0px; right: 8px;" do %>
        <i class="fa-solid fa-pen-to-square" style="color: #00b8ff; font-size: 20px;"></i>
      <% end %>
    </div>
  <% end %>

    <%= link_to new_folder_path, style: "position:absolute; top: 28px; right: 23px;" do %>
      <i class="fa-solid fa-folder-plus" style="color: #38b4ff; font-size: 36px;"></i>
    <% end %>
</div>

app/views/folders/new.html.erb
<div class="container-folder" >

  <div class="card">
    <h3>New Collection</h3>
    <br>
    <%= simple_form_for @folder do |f| %>
      <%= f.input :name, label: false, placeholder: "What's your collection called?" %>
      <br>
      <%= f.button :submit, "Create New Collection", class: "d-block btn-small text-decoration-none", style: "margin-bottom: 16px"%>

    <% end %>
  </div>
</div>

app/views/folders/show.html.erb
<div style="padding: 30px 0px">

  <h2>Your <%= @folder.name %> Spots</h2>
  <% @spots.each do |spot| %>
    <div class="fav-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= asset_path(spot.photo) %>)">
      <%= link_to spot_path(spot.id), style:"text-decoration:none; color:white;" do %>
        <p><%= spot.name %></p>
      <% end %>
    </div>
  <% end %>
</div>