config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  patch 'spots/:id', to: "spots#update"

  resources :spots, only: %i[index show] do
    member do
      post 'toggle_favorite', to: "spots#toggle_favorite"
      post 'dislike', to: "spots#dislike"
      post 'update_state'
      resources :favorite_folders, only: :create
    end

    resources :favorites, only: :index
  end

  resources :folders
  resources :users, only: :update

  get '/cats', to: "pages#cats"
  get '/profile', to: 'pages#profile'
  get '/favorites', to: 'spots#favorites'

  resources :favorites, only: :update
  # get '/bookmarksfolders', to: 'folders#index', as: :folders
  # get '/bookmarks/folders/:id', to: 'folders#show', as: :folder
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if controller_name == 'spots' && action_name == 'index' %>
 <div class='footer-container'>
  <%= link_to root_path, class: "homepage-icon" do %>
    <i class="fa-solid fa-house" style='color:#35B5FF; font-size: 30px;'></i>
  <% end %>
  <%= link_to favorites_path, class: "homepage-icon" do %>
    <i class="fa-solid fa-heart" style='color:lightgrey; font-size: 30px;'></i>
  <% end %>
  <%= link_to folders_path, class: "homepage-icon" do %>
    <i class="fa-solid fa-bookmark" style='color:lightgrey; font-size: 30px;'></i>
  <% end %>
  <%= link_to profile_path, class: "homepage-icon" do %>
    <i class="fa-solid fa-user" style='color:lightgrey; font-size: 30px;'></i>
  <% end %>
</div>
<% elsif controller_name == 'spots' && action_name == 'favorites' %>
  <div class='footer-container'>
    <%= link_to root_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-house" style='color:lightgrey; font-size: 30px;'></i>
    <% end %>
    <%= link_to favorites_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-heart" style='color:#35B5FF; font-size: 30px;'></i>
    <% end %>
    <%= link_to folders_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-bookmark" style='color:lightgrey; font-size: 30px'></i>
    <% end %>
    <%= link_to profile_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-user" style='color:lightgrey; font-size: 30px;'></i>
    <% end %>
  </div>
<% elsif controller_name == 'folders' && action_name == 'index'%>
  <div class='footer-container'>
    <%= link_to root_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-house" style='color:lightgrey; font-size: 30px;'></i>
    <% end %>
    <%= link_to favorites_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-heart" style='color:lightgrey; font-size: 30px;'></i>
    <% end %>
    <%= link_to folders_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-bookmark" style='color:#35B5FF; font-size: 30px'></i>

    <% end %>
    <%= link_to profile_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-user" style='color:lightgrey; font-size: 30px;'></i>
    <% end %>
  </div>
<% else controller_name == 'pages' && action_name == 'profile' %>
  <div class='footer-container'>
    <%= link_to root_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-house" style='color:lightgrey; font-size: 30px;'></i>
    <% end %>
    <%= link_to favorites_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-heart" style='color:lightgrey; font-size: 30px;'></i>
    <% end %>
    <%= link_to folders_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-bookmark" style='color:lightgrey; font-size: 30px'></i>
    <% end %>
    <%= link_to profile_path, class: "homepage-icon" do %>
      <i class="fa-solid fa-user" style='color:#35B5FF; font-size: 30px;'></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for current_user do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_like_button.html.erb
<div
  class="like-icon mx-2 <%= current_user.favorited?(spot) ? 'red' : '' %>"
  data-id="<%= spot.id %>">
  <i class="fas fa-heart"></i>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid justify-content-center">
    <%= link_to spots_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>
</div>